const productsdata = [
    {
        _id: "1",
        name:"Men's Long Sleeve Executive Oxford Dress Shirt - Long-sleeved T-shirt",
        image:"https://www.kindpng.com/picc/m/334-3341347_mens-long-sleeve-executive-oxford-dress-shirt-long.png",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        price:300,
        countInStock: 3,
        rating: 4,
        numReviews:4,
    },
    {
        _id: "2",
        name:"Adams Check Shirt - Mens White Dress Shirt With Blue Windowpane Box Checks",
        image:"https://www.kindpng.com/picc/m/722-7226600_adams-check-shirt-mens-white-dress-shirt-with.png",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        price:350,
        countInStock: 10,
        rating: 2,
        numReviews:2,
    },
    {
        _id: "3",
        name:"Mens Hoodie Forest Green Manmade Bonesmen Apparel Clothing",
        image:"https://www.kindpng.com/picc/m/334-3341376_mens-hoodie-forest-green-manmade-bonesmen-apparel-clothing.png",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        price:550,
        countInStock: 0,
        rating: 3.5,
        numReviews:3,
    },
    {
        _id: "4",
        name:"Bomber Jacket For Men Png Clipart - Lightweight Cotton Bomber Jacket",
        image:"https://www.kindpng.com/picc/m/174-1747429_bomber-jacket-for-men-png-clipart-lightweight-cotton.png",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        price:600,
        countInStock: 10,
        rating: 5,
        numReviews:9,
    },
    {
        _id: "5",
        name:"3 In 1 Waterproof Coat Jacket Mens",
        image:"https://www.kindpng.com/picc/m/579-5793617_3-in-1-waterproof-coat-jacket-mens-hd.png",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        price:600,
        countInStock: 10,
        rating: 2.5,
        numReviews:9,
    },
    // {
    //     _id: "6",
    //     name:"Leather Winter Coat",
    //     image:"https://www.kindpng.com/picc/m/781-7812274_leather-winter-coat-png-image-jackets-for-mens.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 4.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "7",
    //     name:"Men Shoes",
    //     image:"https://www.kindpng.com/picc/m/357-3577815_men-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0,
    //     numReviews:9,
    // },
    // {
    //     _id: "8",
    //     name:"Black Sneakers",
    //     image:"https://www.kindpng.com/picc/m/357-3577784_black-sneakers-allbird-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "1",
    //     name:"Men's Long Sleeve Executive Oxford Dress Shirt - Long-sleeved T-shirt",
    //     image:"https://www.kindpng.com/picc/m/334-3341347_mens-long-sleeve-executive-oxford-dress-shirt-long.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:300,
    //     countInStock: 3,
    //     rating: 4,
    //     numReviews:4,
    // },
    // {
    //     _id: "2",
    //     name:"Adams Check Shirt - Mens White Dress Shirt With Blue Windowpane Box Checks",
    //     image:"https://www.kindpng.com/picc/m/722-7226600_adams-check-shirt-mens-white-dress-shirt-with.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:350,
    //     countInStock: 10,
    //     rating: 2,
    //     numReviews:2,
    // },
    // {
    //     _id: "3",
    //     name:"Mens Hoodie Forest Green Manmade Bonesmen Apparel Clothing",
    //     image:"https://www.kindpng.com/picc/m/334-3341376_mens-hoodie-forest-green-manmade-bonesmen-apparel-clothing.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:550,
    //     countInStock: 0,
    //     rating: 3.5,
    //     numReviews:3,
    // },
    // {
    //     _id: "4",
    //     name:"Bomber Jacket For Men Png Clipart - Lightweight Cotton Bomber Jacket",
    //     image:"https://www.kindpng.com/picc/m/174-1747429_bomber-jacket-for-men-png-clipart-lightweight-cotton.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 5,
    //     numReviews:9,
    // },
    // {
    //     _id: "5",
    //     name:"3 In 1 Waterproof Coat Jacket Mens",
    //     image:"https://www.kindpng.com/picc/m/579-5793617_3-in-1-waterproof-coat-jacket-mens-hd.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 2.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "6",
    //     name:"Leather Winter Coat",
    //     image:"https://www.kindpng.com/picc/m/781-7812274_leather-winter-coat-png-image-jackets-for-mens.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 4.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "7",
    //     name:"Men Shoes",
    //     image:"https://www.kindpng.com/picc/m/357-3577815_men-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0,
    //     numReviews:9,
    // },
    // {
    //     _id: "8",
    //     name:"Black Sneakers",
    //     image:"https://www.kindpng.com/picc/m/357-3577784_black-sneakers-allbird-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0.5,
    //     numReviews:9,
    // }, {
    //     _id: "1",
    //     name:"Men's Long Sleeve Executive Oxford Dress Shirt - Long-sleeved T-shirt",
    //     image:"https://www.kindpng.com/picc/m/334-3341347_mens-long-sleeve-executive-oxford-dress-shirt-long.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:300,
    //     countInStock: 3,
    //     rating: 4,
    //     numReviews:4,
    // },
    // {
    //     _id: "2",
    //     name:"Adams Check Shirt - Mens White Dress Shirt With Blue Windowpane Box Checks",
    //     image:"https://www.kindpng.com/picc/m/722-7226600_adams-check-shirt-mens-white-dress-shirt-with.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:350,
    //     countInStock: 10,
    //     rating: 2,
    //     numReviews:2,
    // },
    // {
    //     _id: "3",
    //     name:"Mens Hoodie Forest Green Manmade Bonesmen Apparel Clothing",
    //     image:"https://www.kindpng.com/picc/m/334-3341376_mens-hoodie-forest-green-manmade-bonesmen-apparel-clothing.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:550,
    //     countInStock: 0,
    //     rating: 3.5,
    //     numReviews:3,
    // },
    // {
    //     _id: "4",
    //     name:"Bomber Jacket For Men Png Clipart - Lightweight Cotton Bomber Jacket",
    //     image:"https://www.kindpng.com/picc/m/174-1747429_bomber-jacket-for-men-png-clipart-lightweight-cotton.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 5,
    //     numReviews:9,
    // },
    // {
    //     _id: "5",
    //     name:"3 In 1 Waterproof Coat Jacket Mens",
    //     image:"https://www.kindpng.com/picc/m/579-5793617_3-in-1-waterproof-coat-jacket-mens-hd.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 2.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "6",
    //     name:"Leather Winter Coat",
    //     image:"https://www.kindpng.com/picc/m/781-7812274_leather-winter-coat-png-image-jackets-for-mens.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 4.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "7",
    //     name:"Men Shoes",
    //     image:"https://www.kindpng.com/picc/m/357-3577815_men-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0,
    //     numReviews:9,
    // },
    // {
    //     _id: "8",
    //     name:"Black Sneakers",
    //     image:"https://www.kindpng.com/picc/m/357-3577784_black-sneakers-allbird-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0.5,
    //     numReviews:9,
    // }, {
    //     _id: "1",
    //     name:"Men's Long Sleeve Executive Oxford Dress Shirt - Long-sleeved T-shirt",
    //     image:"https://www.kindpng.com/picc/m/334-3341347_mens-long-sleeve-executive-oxford-dress-shirt-long.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:300,
    //     countInStock: 3,
    //     rating: 4,
    //     numReviews:4,
    // },
    // {
    //     _id: "2",
    //     name:"Adams Check Shirt - Mens White Dress Shirt With Blue Windowpane Box Checks",
    //     image:"https://www.kindpng.com/picc/m/722-7226600_adams-check-shirt-mens-white-dress-shirt-with.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:350,
    //     countInStock: 10,
    //     rating: 2,
    //     numReviews:2,
    // },
    // {
    //     _id: "3",
    //     name:"Mens Hoodie Forest Green Manmade Bonesmen Apparel Clothing",
    //     image:"https://www.kindpng.com/picc/m/334-3341376_mens-hoodie-forest-green-manmade-bonesmen-apparel-clothing.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:550,
    //     countInStock: 0,
    //     rating: 3.5,
    //     numReviews:3,
    // },
    // {
    //     _id: "4",
    //     name:"Bomber Jacket For Men Png Clipart - Lightweight Cotton Bomber Jacket",
    //     image:"https://www.kindpng.com/picc/m/174-1747429_bomber-jacket-for-men-png-clipart-lightweight-cotton.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 5,
    //     numReviews:9,
    // },
    // {
    //     _id: "5",
    //     name:"3 In 1 Waterproof Coat Jacket Mens",
    //     image:"https://www.kindpng.com/picc/m/579-5793617_3-in-1-waterproof-coat-jacket-mens-hd.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 2.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "6",
    //     name:"Leather Winter Coat",
    //     image:"https://www.kindpng.com/picc/m/781-7812274_leather-winter-coat-png-image-jackets-for-mens.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 4.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "7",
    //     name:"Men Shoes",
    //     image:"https://www.kindpng.com/picc/m/357-3577815_men-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0,
    //     numReviews:9,
    // },
    // {
    //     _id: "8",
    //     name:"Black Sneakers",
    //     image:"https://www.kindpng.com/picc/m/357-3577784_black-sneakers-allbird-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0.5,
    //     numReviews:9,
    // }, {
    //     _id: "1",
    //     name:"Men's Long Sleeve Executive Oxford Dress Shirt - Long-sleeved T-shirt",
    //     image:"https://www.kindpng.com/picc/m/334-3341347_mens-long-sleeve-executive-oxford-dress-shirt-long.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:300,
    //     countInStock: 3,
    //     rating: 4,
    //     numReviews:4,
    // },
    // {
    //     _id: "2",
    //     name:"Adams Check Shirt - Mens White Dress Shirt With Blue Windowpane Box Checks",
    //     image:"https://www.kindpng.com/picc/m/722-7226600_adams-check-shirt-mens-white-dress-shirt-with.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:350,
    //     countInStock: 10,
    //     rating: 2,
    //     numReviews:2,
    // },
    // {
    //     _id: "3",
    //     name:"Mens Hoodie Forest Green Manmade Bonesmen Apparel Clothing",
    //     image:"https://www.kindpng.com/picc/m/334-3341376_mens-hoodie-forest-green-manmade-bonesmen-apparel-clothing.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:550,
    //     countInStock: 0,
    //     rating: 3.5,
    //     numReviews:3,
    // },
    // {
    //     _id: "4",
    //     name:"Bomber Jacket For Men Png Clipart - Lightweight Cotton Bomber Jacket",
    //     image:"https://www.kindpng.com/picc/m/174-1747429_bomber-jacket-for-men-png-clipart-lightweight-cotton.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 5,
    //     numReviews:9,
    // },
    // {
    //     _id: "5",
    //     name:"3 In 1 Waterproof Coat Jacket Mens",
    //     image:"https://www.kindpng.com/picc/m/579-5793617_3-in-1-waterproof-coat-jacket-mens-hd.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 2.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "6",
    //     name:"Leather Winter Coat",
    //     image:"https://www.kindpng.com/picc/m/781-7812274_leather-winter-coat-png-image-jackets-for-mens.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 4.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "7",
    //     name:"Men Shoes",
    //     image:"https://www.kindpng.com/picc/m/357-3577815_men-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0,
    //     numReviews:9,
    // },
    // {
    //     _id: "8",
    //     name:"Black Sneakers",
    //     image:"https://www.kindpng.com/picc/m/357-3577784_black-sneakers-allbird-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0.5,
    //     numReviews:9,
    // }, {
    //     _id: "1",
    //     name:"Men's Long Sleeve Executive Oxford Dress Shirt - Long-sleeved T-shirt",
    //     image:"https://www.kindpng.com/picc/m/334-3341347_mens-long-sleeve-executive-oxford-dress-shirt-long.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:300,
    //     countInStock: 3,
    //     rating: 4,
    //     numReviews:4,
    // },
    // {
    //     _id: "2",
    //     name:"Adams Check Shirt - Mens White Dress Shirt With Blue Windowpane Box Checks",
    //     image:"https://www.kindpng.com/picc/m/722-7226600_adams-check-shirt-mens-white-dress-shirt-with.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:350,
    //     countInStock: 10,
    //     rating: 2,
    //     numReviews:2,
    // },
    // {
    //     _id: "3",
    //     name:"Mens Hoodie Forest Green Manmade Bonesmen Apparel Clothing",
    //     image:"https://www.kindpng.com/picc/m/334-3341376_mens-hoodie-forest-green-manmade-bonesmen-apparel-clothing.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:550,
    //     countInStock: 0,
    //     rating: 3.5,
    //     numReviews:3,
    // },
    // {
    //     _id: "4",
    //     name:"Bomber Jacket For Men Png Clipart - Lightweight Cotton Bomber Jacket",
    //     image:"https://www.kindpng.com/picc/m/174-1747429_bomber-jacket-for-men-png-clipart-lightweight-cotton.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 5,
    //     numReviews:9,
    // },
    // {
    //     _id: "5",
    //     name:"3 In 1 Waterproof Coat Jacket Mens",
    //     image:"https://www.kindpng.com/picc/m/579-5793617_3-in-1-waterproof-coat-jacket-mens-hd.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 2.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "6",
    //     name:"Leather Winter Coat",
    //     image:"https://www.kindpng.com/picc/m/781-7812274_leather-winter-coat-png-image-jackets-for-mens.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 4.5,
    //     numReviews:9,
    // },
    // {
    //     _id: "7",
    //     name:"Men Shoes",
    //     image:"https://www.kindpng.com/picc/m/357-3577815_men-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0,
    //     numReviews:9,
    // },
    // {
    //     _id: "8",
    //     name:"Black Sneakers",
    //     image:"https://www.kindpng.com/picc/m/357-3577784_black-sneakers-allbird-shoes-hd-png-download.png",
    //     description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //     price:600,
    //     countInStock: 10,
    //     rating: 0.5,
    //     numReviews:9,
    // },
];

export default productsdata;